### ISSUE TITLE
ComposableInfoCard is written ComposableInforCard

### ISSUE THREAD

**Issue by khonager** [google-developer-training/basic-android-kotlin-compose-training-practice-problems#1]
https://github.com/google-developer-training/basic-android-kotlin-compose-training-practice-problems/tree/main/Unit%201/Pathway%203/ComposeQuadrant

**Comment by osuleymanova** [comment]
Hello @khonager,

Thank you for reaching out to us and reporting this typo. It is fixed:

![Screenshot 2023-04-04 at 2 53 52 PM](https://user-images.githubusercontent.com/86437155/229931351-2cdfbf04-4fbf-4640-8396-509b27a0a215.png)
